ALTER TABLE surveys MODIFY name VARCHAR(255) NOT NULL;

ALTER TABLE questions MODIFY type VARCHAR(255) NOT NULL;
ALTER TABLE questions MODIFY shortName VARCHAR(255) NOT NULL;
ALTER TABLE questions MODIFY label VARCHAR(255) NOT NULL;

ALTER TABLE nodes MODIFY type VARCHAR(255) NOT NULL;
ALTER TABLE nodes MODIFY username VARCHAR(255) NOT NULL;
ALTER TABLE nodes MODIFY password VARCHAR(255) NOT NULL;
ALTER TABLE nodes MODIFY first_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY last_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY mid_name VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY addr1 VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY addr2 VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY city VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY state VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY country VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY zipcode VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY email VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY phone VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY cell VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY fax VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY department VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY organization VARCHAR(255) DEFAULT NULL;
ALTER TABLE nodes MODIFY unit VARCHAR(255) DEFAULT NULL;

ALTER TABLE roles MODIFY name VARCHAR(255) NOT NULL;

ALTER TABLE groups MODIFY name VARCHAR(255) NOT NULL;

ALTER TABLE activities MODIFY predicate VARCHAR(255) NOT NULL;